### ISSUE TITLE
How to use AES mode ECB with ZeroPadding

### ISSUE THREAD

**Issue by LucasManerich** [leocavalcante/encrypt#135]
I have this code in JavaScript:

```
encode(text, key) {
  let cipher = CryptoJS.enc.Utf8.parse(text);
  let flags = CryptoJS.enc.Utf8.parse('');

  let result = CryptoJS.AES.encrypt(key, cipher, { iv: flags, mode: CryptoJS.mode.ECB, padding: CryptoJS.pad.ZeroPadding });
  return result.toString();
}
```
I need to run on DART but this package is not solving my problem, anyone can help me?

**Comment by leocavalcante** [comment]
https://github.com/leocavalcante/encrypt#nozero-padding

**Comment by LucasManerich** [comment]
@leocavalcante padding: null is not working for me.

**JS:**
```
let text = "user";
let key = CryptoJS.enc.Utf8.parse("Get&AAuthenti&Aau903AutH");
let iv = CryptoJS.enc.Utf8.parse("");

CryptoJS.AES.encrypt(text, key, { iv: iv, mode: CryptoJS.mode.ECB, padding: CryptoJS.pad.ZeroPadding })
```

Result is: UNN5TgYmtFFnxLRepnwkvA==

**Dart:**
```
final key = Key.fromUtf8("Get&AAuthenti&Aau903AutH");
final iv = IV.fromUtf8("");
final encrypter = Encrypter(AES(key, mode: AESMode.ecb, padding: null));
    
final encrypted = encrypter.encrypt("user", iv: iv);
```

Result is an exception:  Unhandled Exception: Invalid argument(s): Input buffer too short

Can you help me?

**Comment by leocavalcante** [comment]
Sorry, I not sure what kind of trickery CryptoJS does because when you use ZeroPadding the input should match the block size based on the key length.

See: https://github.com/brix/crypto-js/issues/282

And: https://stackoverflow.com/questions/61717485/incorrect-decrypted-string-implemented-using-aes-ecb-nopadding-and-base-64-with/61737626#61737626
