### ISSUE TITLE
Non-fatal Exception: java.lang.Exception: NoSuchMethodError: The getter 'length' was called on null.

### ISSUE THREAD

**Issue by Legolaszstudio** [leocavalcante/encrypt#145]
Some of my users are experiencing issues when they try to use my application. I save their username and password, and when the code tries to decrypt it they get this error.

```
Non-fatal Exception: java.lang.Exception: NoSuchMethodError: The getter 'length' was called on null.
Receiver: null
Tried calling: length
       at .new(encrypted.dart:21)
       at .new(encrypted.dart:57)
       at _LoadingPageState.onLoad(loading_screen.dart:85)
```

Here is my piece of code that throws the error: 

```
final iv = encrypt.IV.fromBase64(prefs.getString("iv"));
decryptedCode = codeEncrypter.decrypt64(prefs.getString("code"), iv: iv);
decryptedUser = userEncrypter.decrypt64(prefs.getString("user"), iv: iv);
decryptedPass = passEncrypter.decrypt64(prefs.getString("password"), iv: iv);
```
Before code execution, it is checked whether these shared preferences exist (and made sure that they return a string). So I think that it is a problem with the encrypt plugin, not with the shared preferences.

Also here is how my encryption works:
```
String encryptedPass = passEncrypter.encrypt(pass, iv: iv).base64;
String encryptedUser = userEncrypter.encrypt(user, iv: iv).base64;
String encryptedCode = codeEncrypter.encrypt(code, iv: iv).base64;
```

The encrypters are same for both code snippets:
```
import 'package:encrypt/encrypt.dart' as encrypt;
var passKey = encrypt.Key.fromUtf8(config.passKey);
var codeKey = encrypt.Key.fromUtf8(config.codeKey);
var userKey = encrypt.Key.fromUtf8(config.userKey);
final passEncrypter = encrypt.Encrypter(encrypt.AES(passKey));
final codeEncrypter = encrypt.Encrypter(encrypt.AES(codeKey));
final userEncrypter = encrypt.Encrypter(encrypt.AES(userKey));
```

And these are the config file keys used for testing (not production keys):
```
String passKey = "NovyNovyNovyNovy"; 
String codeKey = "NovyNovyNovyNovy"; 
String userKey = "NovyNovyNovyNovy"; 
String iv = 'yyyyyyyyyyyyyyyy';
```

Maybe the f***ed up iv is the problem?

**Comment by Legolaszstudio** [comment]
Update, my friend used A/B testing where the iv was generated like so:
```
final iv = encrypt.IV.fromLength(16);
prefs.setString("iv", iv.base64);
```
And the issue still occurred at production.

**Comment by leocavalcante** [comment]
Analyzing the stack trace in the provided message, it seams something when it tries to decode a base64 string. Do you have sure the IV is a base64 string?

I really don't know how to address this issue, at a library level, despite just throwing a more friendly exception telling that is an invalid base64 string.

Try calling `base64.decode(ivString)` without `encrypt`. Also you could try wrap this call in try-catch block and report to something like Sentry (or you current logger) what was the base64 string it tried to decode and check if it is a valid array of bytes instead of null.

Also, if you could create a small snippet that reproduces the error it would be very helpful to find where and what is bug exactly.
