### ISSUE TITLE
I can't decrypt the text in 5.0.3 😕

### ISSUE THREAD

**Issue by eng-najm** [leocavalcante/encrypt#318]
### **my code** 

Future<String> uncodingthetext(String keyg, msg) async {

  final key = Key.fromUtf8('12345678213543543254343432435434');
  final iv = IV.fromSecureRandom(16);
  final encrypter = Encrypter(AES(key));
  final decrypted =  encrypter.decrypt64('sOyElxUKoxK4EjTEJms7PE/VIpuxfqNqVPsQdEsuWMEJ60ArKBGlGpANOFDVD73o8y3iZbd8kgjyS9eABXiIxQ==', iv: iv);
  print(decrypted);
return decrypted ;

  }
  
**The erorr :**
 Invalid or corrupted pad block

 Note : "All the data I entered is correct, yet this error appears." .

**Comment by fuyunmanbu** [comment]
I encountered similar problems, I found that 5.0.3 after each encryption results are different

**Comment by najm-x** [comment]
> I encountered similar problems, I found that 5.0.3 after each encryption results are different

So, what is the solution?

**Comment by fuyunmanbu** [comment]
Continue to use 5.0.2



发自我的iPhone


------------------ Original ------------------
From: najm-flutter ***@***.***&gt;
Date: Mon,Oct 16,2023 5:44 PM
To: leocavalcante/encrypt ***@***.***&gt;
Cc: fuyunmanbu ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [leocavalcante/encrypt] I can't decrypt the text in 5.0.3 �� (Issue #318)





  
I encountered similar problems, I found that 5.0.3 after each encryption results are different
  
So, what is the solution?

**Comment by najm-x** [comment]
> Continue to use 5.0.2 发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: najm-flutter ***@***.***&gt; Date: Mon,Oct 16,2023 5:44 PM To: leocavalcante/encrypt ***@***.***&gt; Cc: fuyunmanbu ***@***.***&gt;, Comment ***@***.***&gt; Subject: Re: [leocavalcante/encrypt] I can't decrypt the text in 5.0.3 �� (Issue #318) I encountered similar problems, I found that 5.0.3 after each encryption results are different So, what is the solution? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

can you give me example how to use it to [decrypt] text like as this R4PxiU3h8YoIRqVowBXm36ZcCeNeZ4s1OvVBTfFlZRdmohQqOpPQqD1YecJeZMAop/hZ4OxqgC1WtwvX/hP9mw==

**Comment by fuyunmanbu** [comment]
I can't help you for the time being. I don't have my computer with me!

发自我的iPhone


------------------ Original ------------------
From: najm-flutter ***@***.***&gt;
Date: Mon,Oct 16,2023 6:50 PM
To: leocavalcante/encrypt ***@***.***&gt;
Cc: fuyunmanbu ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [leocavalcante/encrypt] I can't decrypt the text in 5.0.3 �� (Issue #318)





  
Continue to use 5.0.2 发自我的iPhone
 …
 ------------------ Original ------------------ From: najm-flutter @.&gt; Date: Mon,Oct 16,2023 5:44 PM To: leocavalcante/encrypt @.&gt; Cc: fuyunmanbu @.&gt;, Comment @.&gt; Subject: Re: [leocavalcante/encrypt] I can't decrypt the text in 5.0.3 �� (Issue #318) I encountered similar problems, I found that 5.0.3 after each encryption results are different So, what is the solution? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
can you give me example how to use it to [decrypt] text like as this R4PxiU3h8YoIRqVowBXm36ZcCeNeZ4s1OvVBTfFlZRdmohQqOpPQqD1YecJeZMAop/hZ4OxqgC1WtwvX/hP9mw==

**Comment by najm-x** [comment]
> I can't help you for the time being. I don't have my computer with me! 发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: najm-flutter ***@***.***&gt; Date: Mon,Oct 16,2023 6:50 PM To: leocavalcante/encrypt ***@***.***&gt; Cc: fuyunmanbu ***@***.***&gt;, Comment ***@***.***&gt; Subject: Re: [leocavalcante/encrypt] I can't decrypt the text in 5.0.3 �� (Issue #318) Continue to use 5.0.2 发自我的iPhone … ------------------ Original ------------------ From: najm-flutter @.&gt; Date: Mon,Oct 16,2023 5:44 PM To: leocavalcante/encrypt @.&gt; Cc: fuyunmanbu @.&gt;, Comment @.&gt; Subject: Re: [leocavalcante/encrypt] I can't decrypt the text in 5.0.3 �� (Issue #318) I encountered similar problems, I found that 5.0.3 after each encryption results are different So, what is the solution? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt; can you give me example how to use it to [decrypt] text like as this R4PxiU3h8YoIRqVowBXm36ZcCeNeZ4s1OvVBTfFlZRdmohQqOpPQqD1YecJeZMAop/hZ4OxqgC1WtwvX/hP9mw== — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

Ok Thank's

**Comment by hatemragab** [comment]
i have same problem Invalid argument(s): Invalid or corrupted pad block

**Comment by vuthasothea** [comment]
I have same problem:

![image](https://github.com/leocavalcante/encrypt/assets/10680557/c3038663-472f-4105-af49-41e5eb465667)

**Comment by chaeMil** [comment]
I get this after upgrading from `5.0.1` to `5.0.3` 

```Unhandled Exception: Invalid argument(s): Invalid or corrupted pad block```

**Comment by leocavalcante** [comment]
Duplicated #314

**Comment by Trung15010802** [comment]
final iv = IV(Uint8List(16));

I use that and it's working
