### ISSUE TITLE
i know key must size 16 bytes. context is 14 bytes. has error.like this

### ISSUE THREAD

**Issue by crny** [leocavalcante/encrypt#79]
i know key must size 16 bytes. context is 14 bytes. has error.like this
`import 'package:encrypt/encrypt.dart';

void main() {
  final key = Key.fromUtf8('128bitkey16bytes');
  final iv = IV.fromLength(8);
  final encrypter = Encrypter(AES(key, mode: AESMode.ctr, padding: null));
  final encrypted = encrypter.encrypt('Hello world'.padRight(14), iv: iv);
}`

_Originally posted by @crny in https://github.com/leocavalcante/encrypt/issues/78#issuecomment-532508156_

**Comment by leocavalcante** [comment]
Since you are not using  padding, what you call 'context' must have a length multiple of your key size.
Your key is 16 bytes and 14 isn't a multiple of 16. Multiples of 16 are: 16, 32, 48, 64 and so on, 14 isn't on this list, 14 isn't a multiple of 16 so you can't use a string with 14 bytes in your context.
To use any arbitrary size of context you should use padding or a stream cipher.
